services:

  redis:
    image: redis:latest

  metadata-service:
    image: "ghcr.io/bsc-dom/dataclay:4.1.1"
    depends_on:
      - redis
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_KV_PORT=6379
      - DATACLAY_ID=4ded5b02-962b-4df1-9b57-a80fe335df5c
    command: python -m dataclay.metadata

  backend:
    image: "ghcr.io/bsc-dom/dataclay:4.1.1"
    depends_on:
      - redis
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_KV_PORT=6379
      - DATACLAY_BACKEND_ID=5265ec08-cfb5-4de5-ba5e-9dda3a4345cf
      - DATACLAY_BACKEND_NAME=dcbackend
      - MQTT_HOST=mqtt5
      - MQTT_PORT=1883
      - MQTT_PRODUCER_ID=dcclient
      - DATACLAY_MEMORY_CHECK_INTERVAL=86400
    command: /usr/bin/sh -c "pip --cache-dir /tmp/pip-cache install -r requirements.txt ; python -m dataclay.backend"
    volumes:
      - ./requirements-backend.txt:/workdir/requirements.txt
      - ./wordcount/wordcount_model:/workdir/wordcount_model:ro
      - ./digits/digits_model:/workdir/digits_model:ro
      - ./broker/broker_model:/workdir/broker_model:ro
      - ./docker-pip-cache:/tmp/pip-cache

  proxy:
    image: "ghcr.io/bsc-dom/dataclay:4.1.1"
    ports:
      - 8676:8676
    depends_on:
      - metadata-service
      - backend
    environment:
      - DATACLAY_PROXY_MDS_HOST=metadata-service
      - DATACLAY_KV_HOST=redis
    command: python -m dataclay.proxy

  proxy_exercise:
    image: "ghcr.io/bsc-dom/dataclay:4.1.1"
    ports:
      - 8677:8676
    depends_on:
      - metadata-service
      - backend
    environment:
      - DATACLAY_PROXY_MDS_HOST=metadata-service
      - DATACLAY_KV_HOST=redis
    command: python -m dataclay.proxy
    volumes:
      - ./proxy/proxy_config.py:/workdir/proxy_config.py
      - ./proxy/middleware.py:/workdir/middleware.py

  # The following is not needed by dataClay, but is used for the `broker` exercises
  mqtt5:
    image: eclipse-mosquitto
    ports:
      # Opening the ports to the host is only used for being able to access the broker from the host
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./broker/config:/mosquitto/config:rw
